Gyro and Acc bandwidth
teamspatzenhirn/zephyr pull request #11
Opened 2022-01-05 13:47 UTC by SMN321

2022-01-05 18:27 UTC, ottojo commented on drivers/sensor/bmi088/bmi088_acc.c
> +    uint8_t conf = (uint8_t) (0xff & (osr << 4 | odr));
bit 7 must always be 1

2022-01-05 18:28 UTC, ottojo commented on drivers/sensor/bmi088/bmi088_acc.h
> +#define BMI088_DEFAULT_OSR  0x0A // no oversampling
das ist laut datenblatt 0x02?

2022-01-05 18:32 UTC, ottojo requested changes

2022-01-05 18:32 UTC, ottojo commented on drivers/sensor/bmi088/bmi088_gyr.c
> +        bw = BMI088_GYR_DEFAULT_BW;
warning wegen ungültiger range

2022-01-05 18:32 UTC, ottojo commented on dts/bindings/sensor/bosch,bmi088-acc.yaml
> +    description: Bandwidth of the internal low-pass filter
```suggestion
    description: Oversampling ratio, influences bandwidth of internal low-pass filter. See value "acc_bwp" in datasheet
```

2022-01-05 18:32 UTC, ottojo commented on dts/bindings/sensor/bosch,bmi088-acc.yaml
> +    description: Bandwidth of the internal low-pass filter
```suggestion
    description: Output data rate, influences bandwidth of internal low-pass filter. See value "acc_odr" in datasheet
```

2022-01-05 18:32 UTC, ottojo commented on dts/bindings/sensor/bosch,bmi088-gyr.yaml
> +    description: Bandwidth of the internal low-pass filter
```suggestion
    description: Bandwidth of the internal low-pass filter, see value "gyro_bw" in datasheet
```

2022-01-06 11:15 UTC, SMN321 commented on drivers/sensor/bmi088/bmi088_acc.c
> +    uint8_t conf = (uint8_t) (0xff & (osr << 4 | odr));
siehe unten

2022-01-06 11:16 UTC, SMN321 commented on drivers/sensor/bmi088/bmi088_gyr.c
> +        bw = BMI088_GYR_DEFAULT_BW;
43e5385c018f41714edad7067e0fe3a53cad9efa

2022-01-07 11:34 UTC, ottojo requested changes

2022-01-07 11:34 UTC, ottojo commented on drivers/sensor/bmi088/bmi088_acc.c
> +        LOG_DBG("Failed to set acc's ODR and OSR to %d", conf);
```suggestion
        LOG_ERR("Failed to set acc's ODR and OSR to %d", conf);
```

2022-01-07 11:34 UTC, ottojo approved these changes

2022-01-07 11:36 UTC, merged