WIP: bmi088 acc
teamspatzenhirn/zephyr pull request #6
Opened 2021-11-18 14:20 UTC by luisuark

Über die TODOs sollte man definitiv noch rüberschauen.
Auch die Berechnung der scale in `bmi088_acc_channel_get` ist vermutlich noch nicht ideal weil da alle möglichen Konvertierungen stattfinden.

2021-11-20 22:34 UTC, ottojo requested changes

2021-11-20 22:34 UTC, ottojo commented on drivers/sensor/bmi088/bmi088_acc.c
> +#define DT_DRV_COMPAT bosch_bmi088
Das muss noch angepasst werden (gyro/acc), und dann braucht dern accelerometer teil auch noch ein eigenes devicetree binding (so wie hier: https://github.com/teamspatzenhirn/zephyr/pull/3/files#diff-1103c68b35b42abeca05d9862326a4a7b49928e42b1cea419de3b9f49e5ecdbc)

2021-11-20 22:34 UTC, ottojo commented on drivers/sensor/bmi088/bmi088_acc.c
> +            },
Ist das so schon getestet? Das datenblatt liest sich für mich so als ob man das dummy byte zwischen senden und empfangen haben sollte (also hier als 2ten eintrag)

2021-11-20 22:34 UTC, ottojo commented on drivers/sensor/bmi088/bmi088_acc.c
> +            .count = buf ? 3 : 2        // If *buf points to null, only send dummy byte and register address
```suggestion
            .count = buf ? 3 : 1        // If *buf points to null, only send register address
```

2021-11-20 22:34 UTC, ottojo commented on drivers/sensor/bmi088/bmi088_acc.c
> +        LOG_DBG("Cannot reboot chip.");
```suggestion
        LOG_ERR("Cannot reboot chip.");
```

2021-11-20 22:34 UTC, ottojo commented on drivers/sensor/bmi088/bmi088_acc.c
> +        LOG_DBG("Failed to read chip id.");
```suggestion
        LOG_ERR("Failed to read chip id.");
```

2021-11-20 22:34 UTC, ottojo commented on drivers/sensor/bmi088/bmi088_acc.c
> +        LOG_DBG("Failed to read chip id.");
```suggestion
        LOG_ERR("Failed to read chip id.");
```

2021-11-20 22:34 UTC, ottojo commented on drivers/sensor/bmi088/bmi088_acc.c
> +        LOG_DBG("Unsupported chip detected (0x%x)!", val);
```suggestion
        LOG_ERR("Unsupported chip detected (0x%x)!", val);
```

2021-11-20 22:34 UTC, ottojo commented on drivers/sensor/bmi088/bmi088_acc.c
> +        LOG_DBG("Cannot set default range for accelerometer.");
```suggestion
        LOG_ERR("Cannot set default range for accelerometer.");
```

2021-11-20 22:34 UTC, ottojo commented on drivers/sensor/bmi088/bmi088_acc.c
> +        LOG_DBG("Cannot switch power mode to normal");
```suggestion
        LOG_ERR("Cannot switch power mode to normal");
```

2021-11-20 22:34 UTC, ottojo commented on drivers/sensor/bmi088/bmi088_acc.c
> +    if (bmi088_acc_reg_field_update(dev, ACC_RANGE,0, BIT(0) | BIT(1) ,BMI088_ACC_DEFAULT_RANGE) < 0) {
```suggestion
    if (bmi088_acc_reg_field_update(dev, ACC_RANGE,0, 0b11 ,BMI088_ACC_DEFAULT_RANGE) < 0) {
```

2021-11-20 22:34 UTC, ottojo commented on drivers/sensor/bmi088/bmi088_acc.c
> +    }
Das würde ich hier nicht bei jedem `fetch` machen, sondern hier einfach die daten auslesen welche gerade da sind, ohne auf neue zu warten.

2021-11-20 22:34 UTC, ottojo commented on drivers/sensor/bmi088/bmi088_acc.c
> +    }
Macht aber vielleicht sinn das nach der initialisierung zu machen (so als einfachen check ob der sensor lebt, die ganze self-check prozedur ist ja eher aufwändig, lass und das erst mal noch nicht machen (man könnte da ein issue für später aufmachen))

2021-11-20 22:40 UTC, ottojo commented on drivers/sensor/bmi088/bmi088_acc.c
> +    const uint16_t scale = (32768 * 1000 * pow(2,(range_value + 1)) * 1.5);
```suggestion
    const uint16_t scale = (32768 * 1000 * (1 << (range_value + 1)) * 1.5);
```

ja nicht schön und so aber `pow()` gibts wohl nur für floating point...

2021-11-20 22:40 UTC, ottojo commented on drivers/sensor/bmi088/bmi088_acc.c
> +    const uint16_t scale = (32768 * 1000 * pow(2,(range_value + 1)) * 1.5);
ah ja wo kommt eigentlich das ` * 1.5` her?

2021-11-20 23:09 UTC, ottojo commented
ich finde das gerade ein bisschen schwer die einheiten-umrechnung nachzuvollziehen, da wir sowieso momentan nur eine scale verwenden, kann man das in eine einzige funktion schmeißen?

2021-11-22 12:05 UTC, luisuark commented on drivers/sensor/bmi088/bmi088_acc.c
> +    }
Okay, dann machen wir das erstmal so wie beim Gyro und gehen davon aus dass der sensor ready ist

2021-11-23 19:03 UTC, ottojo approved these changes

2021-11-23 19:03 UTC, merged